### ISSUE TITLE
SAP item excel 欄位重整

### ISSUE THREAD

**Issue by leader2345520** [leader2345520/SyncFormsApp#7]
PO number 空白的才要留著

固定值
![image](https://user-images.githubusercontent.com/35731887/167094749-134011bc-971c-43b1-851e-c05e54610792.png)
![image](https://user-images.githubusercontent.com/35731887/167322261-aa902e3b-8b2e-476f-b073-92364bd60c4b.png)

**Comment by leader2345520** [comment]
private void btnBrowseSap_Click(object sender, EventArgs e)
 class BaseModel
 class SapModel

**Comment by leah833011** [comment]
金額部分不能貼上
